const suppliedAt = new Date("2026-09-13T00:00:00Z");

function row(
  key: string,
  eventDate: string,
  country: string,
  city: string,
  venue: string,
  description: string,
  disruptionPotential: "Moderate" | "High",
  eventType: string,
  startTime: string | null = null,
) {
  return {
    sourceName: "analyst_schedule_upload",
    sourceUrl: "",
    sourceTitle: description,
    sourcePublishedAt: suppliedAt,
    eventDate: new Date(`${eventDate}T00:00:00Z`),
    country,
    city,
    venue,
    eventType,
    issue: null,
    organiser: null,
    description,
    startTime,
    attendance: null,
    disruptionPotential,
    confidence: disruptionPotential === "High" ? "High" : "Moderate",
    status: "Planned",
    collectedAt: suppliedAt,
    searchCompletedAt: suppliedAt,
    dedupKey: `analyst_schedule_sep2026_${key}`,
  };
}

/** Exact 13-row schedule supplied by the owner on 13 September 2026. */
export const SEPTEMBER_2026_PROTEST_SCHEDULE = [
  row(
    "india_jalna_mumbai_15",
    "2026-09-15",
    "India",
    "Mumbai",
    "Jalna → Mumbai route",
    "Maratha reservation mobilisation begins movement toward Mumbai. Manoj Jarange supporters depart toward Mumbai, with staged stops through Beed, Ahilyanagar, Pune and Raigad before the main protest.",
    "High",
    "Mobilisation",
  ),
  row(
    "australia_sydney_15",
    "2026-09-15",
    "Australia",
    "Sydney",
    "NSW Parliament, Sydney",
    "Anti abortion rally, 1800–1900 outside Parliament House ahead of a parliamentary vote.",
    "Moderate",
    "Rally",
    "18:00",
  ),
  row(
    "australia_brisbane_16",
    "2026-09-16",
    "Australia",
    "Brisbane",
    "Brisbane City",
    "Palestine rally and petition delivery, scheduled for 1630.",
    "Moderate",
    "Rally",
    "16:30",
  ),
  row(
    "australia_sydney_17",
    "2026-09-17",
    "Australia",
    "Sydney",
    "Sydney",
    "Student strike against Pauline Hanson, scheduled from 1300.",
    "Moderate",
    "Student strike",
    "13:00",
  ),
  row(
    "japan_kyoto_18",
    "2026-09-18",
    "Japan",
    "Kyoto",
    "Kyoto",
    "Anti war peace demonstration, beginning 1800. Similar constitutional and anti war actions are scheduled across several Japanese cities that evening.",
    "Moderate",
    "Demonstration",
    "18:00",
  ),
  row(
    "india_mumbai_19",
    "2026-09-19",
    "India",
    "Mumbai",
    "Azad Maidan, Mumbai",
    "Maratha reservation protest and indefinite hunger strike begins. Supporters arriving from the multi day mobilisation are expected to concentrate in Mumbai.",
    "High",
    "Protest",
  ),
  row(
    "japan_tokyo_diet_19",
    "2026-09-19",
    "Japan",
    "Tokyo",
    "National Diet, Tokyo",
    "9.19 anti war and constitutional mobilisation, 1530 outside the Diet main gate, marking 11 years since the security legislation campaign. Related actions are planned nationwide.",
    "High",
    "Mobilisation",
    "15:30",
  ),
  row(
    "new_zealand_auckland_19",
    "2026-09-19",
    "New Zealand",
    "Auckland",
    "Albert Park → Queen Street → Te Komititanga Square, Auckland",
    "March for Nature, gathering 1300 and marching from about 1330 against changes affecting conservation land.",
    "High",
    "March",
    "13:00",
  ),
  row(
    "australia_sydney_hyde_19",
    "2026-09-19",
    "Australia",
    "Sydney",
    "Hyde Park, Sydney",
    "Sydney Walk for Life, scheduled from 1400.",
    "Moderate",
    "March",
    "14:00",
  ),
  row(
    "australia_perth_19",
    "2026-09-19",
    "Australia",
    "Perth",
    "Forrest Place, Perth",
    "Iranian community freedom and justice gathering, 1600–1800.",
    "Moderate",
    "Gathering",
    "16:00",
  ),
  row(
    "australia_wollongong_19",
    "2026-09-19",
    "Australia",
    "Wollongong",
    "Wollongong",
    "RAWKUS Against AUKUS / Palestine solidarity action, scheduled from 1600.",
    "Moderate",
    "Protest action",
    "16:00",
  ),
  row(
    "japan_tokyo_shinjuku_20",
    "2026-09-20",
    "Japan",
    "Tokyo",
    "Shinjuku, Tokyo",
    "“Protest the chaotic politics” street action, 1500–1630 in the Shinjuku pedestrian zone, followed by a further peace and freedom action until 1800.",
    "High",
    "Street protest",
    "15:00",
  ),
  row(
    "japan_sendai_20",
    "2026-09-20",
    "Japan",
    "Sendai",
    "Kakyo-in Green Space, Sendai",
    "Gaza / Palestine street march, 1600–1730 from Kakyo-in Green Space.",
    "Moderate",
    "March",
    "16:00",
  ),
] as const;