import { Router, type IRouter } from "express";
import healthRouter from "./health";
import incidentsRouter from "./incidents";
import strikesRouter from "./strikes";
import sourcesRouter from "./sources";
import reportsRouter from "./reports";
import spotReportsRouter from "./spotReports";
import countriesRouter from "./countries";
import baselinesRouter from "./baselines";
import proseRouter from "./prose";
import reportIncidentSummariesRouter from "./reportIncidentSummaries";
import dashboardRouter from "./dashboard";
import marketPricesRouter from "./marketPrices";
import maritimeMovementRouter from "./maritimeMovement";
import liveuamapRouter from "./liveuamap";
import reliefwebReportsRouter from "./reliefwebReports";
import maritimeSecurityEventsRouter from "./maritimeSecurityEvents";
import integrationsRouter from "./integrations";
import adminRouter from "./admin";
import backfillRouter from "./backfill";
import cardsRouter from "./cards";

const router: IRouter = Router();

router.use(healthRouter);
router.use(adminRouter);
router.use(backfillRouter);
router.use(incidentsRouter);
router.use(strikesRouter);
router.use(sourcesRouter);
router.use(reportsRouter);
router.use(spotReportsRouter);
router.use(baselinesRouter);
router.use(proseRouter);
router.use(reportIncidentSummariesRouter);
router.use(countriesRouter);
router.use(dashboardRouter);
router.use(marketPricesRouter);
router.use(maritimeMovementRouter);
router.use(liveuamapRouter);
router.use(reliefwebReportsRouter);
router.use(maritimeSecurityEventsRouter);
router.use(integrationsRouter);
router.use(cardsRouter);

export default router;
