import { pgTable, serial, integer, text, jsonb, timestamp } from "drizzle-orm/pg-core";

// Per-incident AI analyst summaries for a TOPIC / CONFLICT / SHIPPING report's
// Related Incidents table, keyed by incident id. Each value is a short factual
// summary grounded only on that incident's own title + summary line (mirrors the
// per-incident summaries the country brief already produces). Generated by the
// shared prose engine (artifacts/api-server/src/lib/countryProse.ts).
export type ReportIncidentSummaryMap = Record<string, string>;

// Cache of AI-generated per-incident summaries, keyed one-row-per-report.
//
// `fingerprint` hashes the exact (canonical, capped) incident set the summaries
// were grounded on plus the prompt version, so when the underlying data changes
// the fingerprint changes and the summaries regenerate — the cache can never go
// stale. `edited` holds analyst overrides bound to the SAME fingerprint; it is
// dropped whenever the summaries are regenerated, so an edit only ever describes
// the data snapshot it was written against.
export const reportIncidentSummariesTable = pgTable("report_incident_summaries", {
  id: serial("id").primaryKey(),
  reportId: integer("report_id").notNull().unique(),
  fingerprint: text("fingerprint").notNull(),
  summaries: jsonb("summaries").$type<ReportIncidentSummaryMap>().notNull(),
  edited: jsonb("edited").$type<ReportIncidentSummaryMap | null>(),
  model: text("model").notNull(),
  generatedAt: timestamp("generated_at", { withTimezone: true }).notNull().defaultNow(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export type ReportIncidentSummaries = typeof reportIncidentSummariesTable.$inferSelect;
export type InsertReportIncidentSummaries = typeof reportIncidentSummariesTable.$inferInsert;
